const CONFIG = {
  MAP_WIDTH: 5000,
  MAP_HEIGHT: 3000,

  ZOOM_MIN: 0.25,
  ZOOM_MAX: 1.8,
  ZOOM_DEFAULT: 0.6,
  PAN_SPEED: 450,

  ISLAND_COUNT: 8,
  ISLAND_CAPTURE_TIME: 6,
  ISLAND_DEFENSE_RANGE: 160,
  ISLAND_DEFENSE_DAMAGE: 10,
  ISLAND_DEFENSE_RATE: 1.0,

  MAIN_BASE_HP: 2500,
  MAIN_BASE_INCOME: 18,
  MAIN_BASE_OIL: 10,
  MAIN_BASE_ENERGY_REGEN: 8,
  MAIN_BASE_MAX_ENERGY: 100,

  STARTING_GOLD: 200,
  SCRAP_LIFETIME: 10,
  SCRAP_VALUE: 30,

  WIN_UPGRADE_CURRENCY: 75,
  LOSS_UPGRADE_CURRENCY: 15,
  WIN_CAPTAIN_CURRENCY: 40,

  DIFFICULTY_STAGES: [
    { name: 'Cadet',         level: 0, winsRequired: 3 },
    { name: 'Officer',       level: 1, winsRequired: 3 },
    { name: 'Commander',     level: 2, winsRequired: 3 },
    { name: 'Captain',       level: 3, winsRequired: 3 },
    { name: 'Admiral',       level: 4, winsRequired: 3 },
    { name: 'Fleet Admiral', level: 5, winsRequired: 3 },
    { name: 'Grand Admiral', level: 6, winsRequired: Infinity },
  ],

  DIFFICULTY_MULT: [
    { buildMult: 1.8, attackMult: 0.65, strategyScore: 0.2, aggressionDelay: 35 },
    { buildMult: 1.5, attackMult: 0.80, strategyScore: 0.35, aggressionDelay: 28 },
    { buildMult: 1.2, attackMult: 0.95, strategyScore: 0.50, aggressionDelay: 22 },
    { buildMult: 1.0, attackMult: 1.10, strategyScore: 0.65, aggressionDelay: 18 },
    { buildMult: 0.85, attackMult: 1.25, strategyScore: 0.78, aggressionDelay: 14 },
    { buildMult: 0.7, attackMult: 1.40, strategyScore: 0.90, aggressionDelay: 10 },
    { buildMult: 0.55, attackMult: 1.58, strategyScore: 1.00, aggressionDelay: 7 },
  ],

  PRACTICE_DIFFICULTY: {
    easy:   { buildMult: 2.0, attackMult: 0.55, strategyScore: 0.1, aggressionDelay: 45 },
    medium: { buildMult: 1.2, attackMult: 0.95, strategyScore: 0.5, aggressionDelay: 22 },
    hard:   { buildMult: 0.8, attackMult: 1.30, strategyScore: 0.85, aggressionDelay: 12 },
  },

  BOATS: {
    scout: {
      id: 'scout',
      name: 'Scout',
      cost: 60,
      oilCost: 1,
      buildTime: 8,
      hp: 120,
      speed: 160,
      attackRange: 145,
      attackDamage: 10,
      attackRate: 1.3,
      visionRange: 330,
      canCapture: false,
      damageType: 'cannon',
      armorType: 'light',
      size: 10,
      unlocked: true,
      description: 'Fast with large vision. Cannot capture islands.',
      ability: {
        id: 'lookout', name: 'Lookout', hotkey: 'Q',
        desc: 'Vision +80% for 6s', cooldown: 20, duration: 6,
      },
    },
    smallBattlecruiser: {
      id: 'smallBattlecruiser',
      name: 'Battlecruiser I',
      cost: 130,
      oilCost: 3,
      buildTime: 15,
      hp: 380,
      speed: 80,
      attackRange: 195,
      attackDamage: 26,
      attackRate: 0.9,
      visionRange: 210,
      canCapture: true,
      damageType: 'cannon',
      armorType: 'medium',
      size: 16,
      unlocked: true,
      description: 'Reliable combat ship. Can capture islands.',
      ability: {
        id: 'cannonade', name: 'Cannonade', hotkey: 'Q',
        desc: 'Fires 4 rapid shots', cooldown: 25, duration: 2,
      },
    },
    mediumBattlecruiser: {
      id: 'mediumBattlecruiser',
      name: 'Battlecruiser II',
      cost: 270,
      oilCost: 5,
      buildTime: 25,
      hp: 720,
      speed: 58,
      attackRange: 245,
      attackDamage: 46,
      attackRate: 0.55,
      visionRange: 225,
      canCapture: true,
      damageType: 'cannon',
      armorType: 'heavy',
      size: 22,
      unlocked: true,
      description: 'Heavy warship. Strong armor. Can capture islands.',
      ability: {
        id: 'armorPlating', name: 'Armor Plating', hotkey: 'Q',
        desc: 'Reduce damage 50% for 8s', cooldown: 35, duration: 8,
      },
    },
    submarine: {
      id: 'submarine',
      name: 'Submarine',
      cost: 200,
      oilCost: 4,
      buildTime: 22,
      hp: 290,
      speed: 68,
      attackRange: 185,
      attackDamage: 70,
      attackRate: 0.38,
      visionRange: 185,
      canCapture: true,
      damageType: 'torpedo',
      armorType: 'medium',
      size: 15,
      unlocked: true,
      description: 'Stealthy torpedo ship. Can submerge to become invisible.',
      ability: {
        id: 'dive', name: 'Dive', hotkey: 'Q',
        desc: 'Invisible for 12s, cannot attack', cooldown: 40, duration: 12,
      },
    },
  },

  DAMAGE_MULT: {
    cannon:  { light: 1.0, medium: 0.80, heavy: 0.60 },
    torpedo: { light: 1.2, medium: 1.10, heavy: 1.00 },
    aerial:  { light: 0.9, medium: 0.85, heavy: 0.90 },
  },

  ISLAND_STAGES: [
    { name: 'Island',   upgradeCost: 0,   income: 8,  oil: 5,  canRepair: false, canBuild: false, hasDefense: false },
    { name: 'Outpost',  upgradeCost: 150, income: 13, oil: 8,  canRepair: true,  canBuild: false, hasDefense: false },
    { name: 'Port',     upgradeCost: 350, income: 20, oil: 12, canRepair: true,  canBuild: true,  hasDefense: false },
    { name: 'Fortress', upgradeCost: 700, income: 28, oil: 16, canRepair: true,  canBuild: true,  hasDefense: true  },
  ],

  WEATHER_INTERVAL_MIN: 50,
  WEATHER_INTERVAL_MAX: 130,
  STORM_DURATION: 22,
  STORM_SPEED_MULT: 0.5,
  STORM_VISION_MULT: 0.6,
};
